/*
Package pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package errors

import (
	"fmt"
	"github.com/apimatic/go-core-runtime/apiError"
)

// Error is a custom error.
// Api Error Exception
type Error struct {
	apiError.ApiError
	Message *string     `json:"message"`
	Errors  interface{} `json:"errors"`
	Request interface{} `json:"request"`
}

// NewError is a constructor for Error.
// It creates and returns a pointer to a new Error instance with the given statusCode and body.
func NewError(
	statusCode int,
	body string) *Error {
	return &Error{
		ApiError: apiError.ApiError{
			StatusCode: statusCode,
			Body:       body,
		},
	}
}

// Error implements the Error method for the error interface.
// It returns a formatted error message for Error.
func (e *Error) Error() string {
	return fmt.Sprintf("Error occured %v", e.Body)
}
